### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by FreekPaans** [infi-nl/everybody-codes#4]
I made a (quick) English translation at: https://github.com/FreekPaans/everybody-codes/blob/master/README.md.

**Comment by jeroenheijmans** [comment]
Nice. 😄 

I guess we could either add a link to this repo ("See fork with English translation [at freekpaans/everybody-codes](https://github.com/FreekPaans/everybody-codes)"), or we could add the translation back to this repo as a second README.
