### ISSUE TITLE
Google maps API key werkt niet zonder ingevuld Billing information voor account

### ISSUE THREAD

**Issue by Akivashi** [infi-nl/everybody-codes#7]
Sinds enige tijd is het niet meer mogelijk Google Maps door middel van een API key direct te gebruiken binnen de opdracht bij een Google account zonder Billing Information. Je loopt dan vrij snel tegen de melding `You must enable Billing on the Google Cloud Project.` aan.

**Comment by jeroenheijmans** [comment]
Goed punt. Ik denk dat we 'm toegankelijker moeten maken, wellicht is OpenStreetmaps makkelijker op te zetten?

**Comment by Akivashi** [comment]
Lijkt me een prima alternatief (is ook al door anderen geopperd).

Als alternatief zouden we elke keer een API key  kunnen providen (en na de bespreking weer verwijderen om misbruik te voorkomen).
